EmpresaProfile/urls.py
from django.urls import path, include
from .views import home_page, register_page, register_attempt, work_detail, hire_student, refuse_student, add_work, \
    fire_student, work_delete, private_control, account_information, account_information_update


# urls de responsabilidade do app EmpresaProfile. app_name é uma referência
# para encontrar as urls mais facilmente

app_name = 'empresa'
urlpatterns = [
    path('', home_page, name='home_page'),
    path('add-work/', add_work, name='add_work'),
    path('register/', register_page, name='register_page'),
    path('register/try/', register_attempt),
    path('account/', account_information, name='account_information'),
    path('account/update/', account_information_update, name='account_information_update'),
    path('<int:work_pk>/', work_detail, name='work_detail'),
    path('<int:work_pk>/delete/', work_delete, name='work_delete'),
    path('<int:work_pk>/control_private/', private_control, name='private_control'),
    path('<int:work_pk>/hire-<int:student_pk>/', hire_student),
    path('<int:work_pk>/refuse-<int:student_pk>/', refuse_student),
    path('<int:work_pk>/fire-<int:student_pk>/', fire_student),
]

WebApp/urls.py
from django.urls import path, include
from .views import home, login_page, login_attempt, register_page, logout_page, profile_page


# urls de responsabilidade do app WebApp. app_name é uma referência
# para encontrar as urls mais facilmente.

app_name = 'webapp'
urlpatterns = [
    path('', home, name='home_page'),
    path('login/', login_page, name='login_page'),
    path('login/try/', login_attempt),
    path('logout/', logout_page, name='logout_page'),
    path('register/', register_page, name='register_page'),
    path('student/', include('EstudanteProfile.urls', namespace='estudante')),
    path('business/', include('EmpresaProfile.urls', namespace='empresa')),
    path('<username>/', profile_page, name='profile_page'),
]

freelance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('WebApp.urls', namespace='webapp'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EmpresaProfile/models.py
from django.db import models
from django.contrib.auth.models import User


class EmpresaProfile(models.Model):
    """
    Objeto representante de uma empresa
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cidade = models.CharField(max_length=35, blank=True)
    area = models.CharField(max_length=50, blank=True)
    description = models.TextField(blank=True, null=True)
    profile_pic = models.ImageField(upload_to='business-profile_pic',
                                    default='profile-placeholder.png')

    def __str__(self):
        return f'{self.user.first_name} ({self.user.username})'

EmpresaProfile/views.py
import magic
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls import reverse
from Trabalhos.models import Trabalho
from .models import EmpresaProfile


@login_required
def home_page(request):
    """
    Renderiza o html da mainpage
    :param request:
    :return: renderização do html
    """

    if not hasattr(request.user, 'empresaprofile'):
        raise Http404

    user = request.user
    user_data = {'user': user, 'add_work_link': reverse('webapp:empresa:add_work'),
                 'proposals': user.empresaprofile.trabalho.all(),
                 'work_detail': reverse('webapp:empresa:home_page')}

    return render(request, 'pages/business-mainpage.html', user_data)


def register_page(request):
    """
    rendereiza o form de cadastro
    :param request:
    :return:
    """

    return render(request, 'pages/business-register-form.html')


def register_attempt(request):
    """
    Tenta criar uma nova empresa
    :param request:
    :return: página de criado com sucesso ou erro de validação ou erro de usuário já existente
    """

    username = request.POST.get('username')
    email = request.POST.get('email')
    first_name = request.POST.get('nome_fantasia')
    last_name = request.POST.get('nome_juridico')
    cidade = request.POST.get('cidade')
    area = request.POST.get('area')
    password = request.POST.get('password')

    if username and username[0] != '@':
        username = '@' + username

    if username is None or email is None or first_name is None or last_name is None \
            or cidade is None or area is None or password is None:
        raise ValidationError('Algum dos valores é inválido')

    check_username = User.objects.filter(username=username).exists()
    check_email = User.objects.filter(email=email).exists()
    if check_username is True or check_email is True:
        return render(request, "pages/business-register-form.html", {'used_username': check_username,
                                                                     'used_email': check_email})
    new_user = User.objects.create_user(username=username, password=password, email=email,
                                        first_name=first_name, last_name=last_name)
    EmpresaProfile.objects.create(user=new_user, cidade=cidade,
                                  area=area)
    login(request, new_user)
    return render(request, 'created-account.html')


@login_required
def add_work(request):
    """
    Cria um trabalho
    :param request:
    :return: Retorna para a pagina inicial
    """
    if not hasattr(request.user, 'empresaprofile'):
        raise Http404

    titulo = request.POST.get('titulo')
    inicio = request.POST.get('inicio')
    fim = request.POST.get('fim')
    pagamento = request.POST.get('pagamento')
    descricao = request.POST.get('descricao')
    requisitos = request.POST.get('requisitos')

    if titulo is None or inicio is None or fim is None or pagamento is None or descricao is None or requisitos is None:
        raise ValidationError('Algum dos valores é inválido')

    Trabalho.objects.create(business=request.user.empresaprofile, titulo=titulo,
                            inicio=inicio, fim=fim, pagamento=pagamento,
                            descricao=descricao, requisitos=requisitos)

    return HttpResponseRedirect(reverse('webapp:home_page'))


@login_required
def work_detail(request, work_pk):
    """
    Renderiza a página de detalhe de um trabalho
    :param request:
    :param work_pk: trabalho em questão
    :return:
    """

    if not hasattr(request.user, 'empresaprofile'):
        raise Http404

    trabalho = request.user.empresaprofile.trabalho.get(pk=work_pk)
    user_data = {'trabalho': trabalho,
                 'current_page': reverse('webapp:empresa:work_detail', kwargs={'work_pk': work_pk})}

    return render(request, 'pages/business-work-detail.html', user_data)


@login_required
def hire_student(request, work_pk, student_pk):
    """
    Separa um estudante
    :param request:
    :param work_pk: trabalho em questão
    :param student_pk: estudante em questão
    :return:
    """

    if not hasattr(request.user, 'empresaprofile'):
        raise Http404

    trabalho = request.user.empresaprofile.trabalho.get(pk=work_pk)
    student = trabalho.inscritos.get(pk=student_pk)
    trabalho.contratados.add(student)
    trabalho.inscritos.remove(student)

    return HttpResponseRedirect(reverse('webapp:empresa:work_detail', kwargs={'work_pk': work_pk}))


@login_required
def refuse_student(request, work_pk, student_pk):
    """
    Recusa um estudante
    :param request:
    :param work_pk: trabalho em questão
    :param student_pk: estudante em questão
    :return:
    """

    if not hasattr(request.user, 'empresaprofile'):
        raise Http404

    trabalho = request.user.empresaprofile.trabalho.get(pk=work_pk)
    student = trabalho.inscritos.get(pk=student_pk)
    trabalho.inscritos.remove(student)

    return HttpResponseRedirect(reverse('webapp:empresa:work_detail', kwargs={'work_pk': work_pk}))


@login_required
def fire_student(request, work_pk, student_pk):
    """
    Retira um estudante dos separados
    :param request:
    :param work_pk: trabalho em questão
    :param student_pk: estudante em questão
    :return:
    """

    if not hasattr(request.user, 'empresaprofile'):
        raise Http404

    trabalho = request.user.empresaprofile.trabalho.get(pk=work_pk)
    student = trabalho.contratados.get(pk=student_pk)
    trabalho.inscritos.add(student)
    trabalho.contratados.remove(student)

    return HttpResponseRedirect(reverse('webapp:empresa:work_detail', kwargs={'work_pk': work_pk}))


@login_required
def work_delete(request, work_pk):
    """
    Delete um trabalho
    :param request:
    :param work_pk: trabalho em questão
    :return:
    """

    if not hasattr(request.user, 'empresaprofile'):
        raise Http404

    trabalho = request.user.empresaprofile.trabalho.get(pk=work_pk).delete()

    return HttpResponseRedirect(reverse('webapp:empresa:home_page'))


@login_required
def private_control(request, work_pk):
    """
    Torna um trabalho público em privado e vice-versa
    :param request:
    :param work_pk: trabalho em questão
    :return:
    """

    if not hasattr(request.user, 'empresaprofile'):
        raise Http404

    trabalho = request.user.empresaprofile.trabalho.get(pk=work_pk)
    trabalho.private = not trabalho.private
    trabalho.save()
    return HttpResponseRedirect(reverse('webapp:empresa:work_detail', kwargs={'work_pk': work_pk}))


@login_required
def account_information(request):
    """
    Renderiza a página de atualizar informações da empresa
    :param request:
    :return:
    """

    if not hasattr(request.user, 'empresaprofile'):
        raise Http404

    return render(request, 'pages/business-account-information.html')


@login_required
def account_information_update(request):
    """
    Atualiza as informações da empresa
    :param request:
    :return:
    """

    if not hasattr(request.user, 'empresaprofile'):
        raise Http404

    user = request.user

    user.first_name = request.POST.get('first_name')
    user.last_name = request.POST.get('last_name')
    user.empresaprofile.cidade = request.POST.get('cidade')
    user.empresaprofile.area = request.POST.get('area')
    user.empresaprofile.description = request.POST.get('descricao')

    if request.FILES.get('profile_pic') is not None \
            and magic.from_buffer(request.FILES.get('profile_pic').read(), mime=True).startswith('image/'):
        user.empresaprofile.profile_pic.save(name=user.username + '_pic', content=request.FILES.get('profile_pic'))

    user.save()
    user.empresaprofile.save()

    return render(request, 'pages/business-account-information.html', {'successfully_modified': True})

EmpresaProfile/templates/pages/business-account-information.html
{% extends "business-navbar.html" %}
{% block title %}
<title>Informações da conta</title>
{% endblock %}
{% block content %}
<!--Formulário-->
<div class="w-full flex justify-center">
    <div class="bg-white flex flex-col w-4/5 md:w-3/5 h-full text-center">
        <!--Título do formulário-->
        <h1 class="mt-8 text-xl md:text-3xl text-purple-900 font-semibold">Atualizar dados</h1>
        <hr class="hr-purple-mini mb-6">
        <!--Conteúdo do formulário-->
        <form method="post" action="{% url 'webapp:empresa:account_information_update' %}" enctype="multipart/form-data" id="form" class="w-full flex flex-col">
            {% csrf_token %}
            <!--Nome da empresa-->
            <div class="flex flex-row mb-4 justify-center flex-wrap">
               <div class="flex flex-col mb-4">
                    <label class="block text-gray-700 font-bold mb-2" for="name">Nome jurídico</label>
                    <input name="first_name" value="{{ user.first_name }}" required class="md:px-12 mx-4 text-center shadow appearance-none border rounded py-2 text-gray-800" id="name" type="text">
                </div>
                <div class="flex flex-col mb-4">
                    <label class="block text-gray-700 font-bold mb-2" for="fantasy-name">Nome fantasia</label>
                    <input name="last_name" value="{{ user.last_name }}" required class="md:px-12 mx-4 text-center shadow appearance-none border rounded py-2 text-gray-800" id="fantasy-name" type="text">
                </div>
            </div>
            <!--Cidade-->
            <div class="flex flex-col mb-4">
                <label class="block text-gray-700 font-bold mb-2" for="city">Cidade da sede</label>
                <input name="cidade" value="{{ user.empresaprofile.cidade }}" required class="mx-4 md:mx-40 lg:mx-64 text-center shadow appearance-none border rounded py-2 text-gray-800" id="city" type="text">
            </div>
            <!--Area-->
            <div class="flex flex-col mb-4">
                <label class="block text-gray-700 font-bold mb-2" for="area">Área de atuação</label>
                <input name="area" value="{{ user.empresaprofile.area }}" required class="mx-4 md:mx-40 lg:mx-64 text-center shadow appearance-none border rounded py-2 text-gray-800" id="area" type="text">
            </div>
            <!--Descrição-->
            <div class="flex flex-col mb-4">
                <label class="block text-gray-700 font-bold mb-2" for="description">Descrição</label>
                <textarea name="descricao" rows="6" cols="60" name="description" class="mx-4 md:mx-40 border shadow rounded">{{ user.empresaprofile.description }}  </textarea>
            </div>
            <div class="mb-4">
                <label>Foto de perfil:</label>
                <input name='profile_pic' type="file" accept="image/*">
            </div>
            <div class="mt-4 mb-8 mx-auto">
                {% if successfully_modified %}
                <span class="text-green-500">Modificado com sucesso!</span>
                <br>
                {% endif %}
                <input type="submit" class="bg-purple-700 hover:bg-purple-900 text-white font-bold py-2 px-5 md:px-8 rounded-full">
            </div>
        </form>
    </div>
</div>
{% endblock %}

EmpresaProfile/templates/pages/business-mainpage.html
{% extends "business-navbar.html" %}
{% block title %}
<title>Home</title>
{% endblock %}
{% block content %}
<div class="w-full flex flex-wrap justify-center">
    <!--Dados do usuário-->
    <div class="w-full md:w-1/5 mb-4 md:mb-0">
        <img src="{{ user.empresaprofile.profile_pic.url }}" alt="imagem de perfil" class="rounded-full w-40 h-40 mt-8 mb-8 mx-auto">
        <div class="w-3/4 ml-auto">
            <span class="font-semibold text-purple-900 text-2xl block">{{ user.first_name }} {{ user.last_name }}</span>
            <span class="text-gray-800 text-sm">{{ user }}</span>
            <p class="text-gray-900 text-sm my-4 w-5/6 text-justify">
                {% if user.empresaprofile.description %}
                    {{ user.empresaprofile.description }}
                {% else %}
                    No description.
                {% endif %}
            </p>
            <span class="text-gray-700 text-sm mb-2 block"><i class="fas fa-code-branch mr-2"></i>Empresa da área "{{ user.empresaprofile.area }}"</span> <!--https://fontawesome.com/icons/code-branch?style=solid-->
            <span class="text-gray-700 text-sm mb-2 block"><i class="fas fa-map-marker-alt mr-2"></i>Situada em "{{ user.empresaprofile.cidade }}"</span> <!--https://fontawesome.com/icons/map-marker-alt?style=solid-->
        </div>
    </div>
    <!--Lista de trabalhos-->
    <div class="w-full md:w-2/5 flex flex-col">
        <button onclick="show_newWork_menu()" class="w-1/3 mb-5 bg-purple-700 mx-auto text-center hover:bg-purple-900 text-white font-bold py-3 mt-5 rounded-full toggle">Novo Trabalho</button>
        {% include "add-work.html" with add_work_link=add_work_link%}
        {% include "work-proposal.html" with proposals=proposals work_detail=work_detail %}
    </div>
</div>
{% endblock %}
{% block scripts %}
{% load staticfiles %}
<script src="{% static "scripts/work_toggle.js" %}"></script>
{% endblock %}

EmpresaProfile/templates/pages/business-register-form.html
{% extends "webapp-navbar.html" %}
{% block content %}
<div class="font-sans flex justify-center h-screen bg-login">
    <div class="w-full lg:w-2/3 xl:w-2/5 my-auto">
        <form method="POST" action="{% url 'webapp:empresa:register_page' %}try/" class="bg-white rounded shadow-lg w-full py-4 px-10 md:px-20" id="form">
            {% csrf_token %}
            <h2 class="text-purple-900 text-center font-semibold text-4xl">Empresa</h2>
            <hr class="hr-purple">
            <div class="text-gray-700 my-3">
                <label class="text-sm font-bold" for="email">E-mail</label>
                <input name="email" required class="shadow border rounded w-full px-3 py-2" id="email" type="email" placeholder="E-mail">
                {% if used_email %}
                <span class="text-red-600">Email já usado</span>
                {% endif %}
            </div>
            <div class="text-gray-700">
                <label class="text-sm font-bold" for="username">Nome de usuário</label>
                <input name="username" required class="shadow rounded w-full px-3 py-2" id="username" type="text" placeholder="Nome de usuário">
                {% if used_username %}
                <span class="text-red-600">Usuário já usado</span>
                {% endif %}
            </div>
            <div class="flex justify-around flex-wrap text-gray-700 my-3">
                <div class="w-full mb-3 md:mb-0 md:w-1/2 md:pr-3">
                    <label class="text-sm font-bold" for="name">Nome jurídico</label>
                    <input name="nome_fantasia" required class="shadow rounded w-full px-3 py-2" id="name" type="text" placeholder="Nome">
                </div>
                <div class="w-full md:w-1/2 md:pl-3">
                    <label class="text-sm font-bold" for="surname">Nome fantasia</label>
                    <input name="nome_juridico" required class="shadow rounded w-full px-3 py-2" id="surname" type="text" placeholder="Sobrenome">
                </div>
            </div>
            <div class="flex flex-wrap text-gray-700 my-3">
                <div class="w-full mb-3 md:mb-0 md:w-1/2 md:pr-3">
                    <label class="text-sm font-bold" for="cidade">Cidade da sede</label>
                    <input name="cidade" maxlength="35" required class="shadow rounded w-full px-3 py-2" id="cidade" type="text" placeholder="Cidade">
                </div>
                <div class="w-full md:w-1/2 md:pl-3">
                    <label class="text-sm font-bold" for="area">Área de atuação</label>
                    <input name="area" maxlength="50" maxlength="10" required class="shadow rounded w-full px-3 py-2" id="area" type="text" placeholder="Área de atuação">
                </select>
                </div>
            </div>
            <div class="flex flex-wrap text-gray-700 my-3 mb-10">
                <div class="w-full mb-3 md:mb-0 md:w-1/2 md:pr-3">
                    <label class="text-sm font-bold" for="password">Senha</label>
                    <input name="password" required class="shadow rounded w-full px-3 py-2" id="password" type="password" placeholder="Senha">
                </div>
                <div class="w-full md:w-1/2 md:pl-3">
                    <label class="text-sm font-bold" for="password-repeated">Repetir senha</label>
                    <input required class="shadow rounded w-full px-3 py-2" id="password-repeated" type="password" placeholder="Repetir senha">
                </div>
            </div>
            <div class="mt-4 mb-8 text-center mt-3">
                <input type="submit" value="Cadastrar" class="bg-purple-700 hover:bg-purple-900 text-white font-bold py-2 px-5 md:px-8 rounded-full">
            </div>
        </form>
    </div>
</div>
{% endblock %}

EmpresaProfile/templates/pages/business-work-detail.html
{% extends 'business-navbar.html' %}
{% block title %}
<title>{{ trabalho.titulo }}</title>
{% endblock %}
{% block content %}
{% load trabalho_extras %}
<!--Dados do trabalho-->
<div class="w-full flex flex-wrap justify-center h-screen py-8 bg-login">
    <div class="w-4/5 xl:w-2/5 flex flex-col bg-white p-8 rounded-lg border-4 border-purple-900">
        <h1 class="text-center text-xl md:text-3xl text-purple-800 font-semibold">{{ trabalho.titulo }}</h1>
        <h2 class="text-center text-purple-800">O trabalho atual está
        {% if trabalho.private %}
            <span class="text-red-500">PRIVADO</span>
        {% else %}
            <span class="text-green-500">PÚBLICO</span>
        {% endif %}
        </h2>
        <hr class="hr-purple-mini mb-12">
        <h2 class="text-lg md:text-xl text-purple-900 font-semibold mb-2">Descrição</h2>
        <p class="text-gray-900 text-justify mb-4">
        {{ trabalho.descricao }}
        </p>
        <h2 class="text-lg md:text-xl text-purple-900 font-semibold mb-2">Requisitos</h2>
        <p class="text-gray-900 text-justify mb-4">
        {{ trabalho.requisitos }}
        </p>
        <h2 class="text-lg md:text-xl text-purple-900 font-semibold mb-2">Outros detalhes</h2>
        <ul class="mb-4">
            <li class="mb-1">
                <span class="font-semibold text-gray-900">Pagamento:</span>
                <span class="text-gray-900">{{ trabalho.pagamento }}</span>
            </li>
            <li class="mb-1">
                <span class="font-semibold text-gray-900">Data de início:</span>
                <span class="text-gray-900">{{ trabalho.inicio }}</span>
            </li>
            <li>
                <span class="font-semibold text-gray-900">Data de término:</span>
                <span class="text-gray-900">{{ trabalho.fim }}</span>
            </li>
        </ul>
        <hr>
        <h2 class="text-lg md:text-xl text-purple-900 font-semibold mb-2">Estudantes separados</h2>
        <ul class="mb-8">
            {% for contratado in trabalho.contratados.all %}
            <li class="mb-1 flex justify-between">
                <div>
                    <a href="{% url 'webapp:profile_page' username=contratado.user %}" class="font-semibold text-gray-900 hover:underline">{{ forloop.counter }}) {{ contratado.user }}: </a>
                    <span class="text-gray-900">{{ contratado.user.email }}</span>
                </div>
                <form method="post" action="{{ current_page|addstr:'fire-'|addstr:contratado.pk|addstr:'/' }}">
                    {% csrf_token %}
                    <button type="submit" class="text-gray-900 text-sm hover:underline">Remover</button>
                </form>
            </li>
            {% endfor %}
        </ul>
        <div class="flex mb-12 justify-center">
            <form method="post" action="{{ current_page|addstr:'control_private/' }}">
                {% csrf_token %}
                <button type="submit" class="bg-gray-700 hover:bg-gray-900 text-white font-bold py-2 px-4 rounded-full ml-2">
                    <span>Tornar</span>
                    {% if trabalho.private %}
                        <span class="text-green-500">PÚBLICO</span>
                    {% else %}
                        <span class="text-red-500">PRIVADO</span>
                    {% endif %}
                </button>
            </form>
            <form method="post" action="{{ current_page|addstr:'delete/' }}">
                {% csrf_token %}
                <button type="submit" class="bg-gray-700 hover:bg-gray-900 text-white font-bold py-2 px-4 rounded-full ml-2">Deletar projeto</button>
            </form>
        </div>
        <h2 class="text-lg md:text-2xl text-center text-purple-900 font-semibold mb-4">Lista dos candidatos</h2>
        {% for subscriber in trabalho.inscritos.all %}
        <!--Candidato-->
        <div class="w-full border border-gray-300 shadow-md py-6 px-8 text-center md:text-left bg-white mb-8">
            <!--Nome do candidato-->
            <a href="{% url 'webapp:profile_page' username=subscriber.user %}" class="no-underline md:text-xl font-semibold text-purple-800 hover:text-purple-600">{{ subscriber.user.first_name }} ({{ subscriber.user }})</a>
            <div class="flex flex-col-reverse md:flex-row-reverse justify-around my-8">
                <!--Descrição-->
                <p class="w-full md:w-3/5 text-sm text-gray-800 text-justify">
                    {{ subscriber.descricao }}
                </p>
                <!--Imagem de perfil-->
                <div class="w-full md:w-auto">
                    <img src="https://mdbootstrap.com/img/Photos/Others/images/90.jpg" alt="logo-empresa" class="rounded-full w-24 h-24 mb-8 md:mb-0 mx-auto">
                </div>
            </div>
            <!--Dados gerais-->
            <div class="w-full md:w-auto float-left">
                <i class="fas fa-graduation-cap mr-2"></i> <!--https://fontawesome.com/icons/graduation-cap?style=solid-->
                <span class="text-sm font-semibold text-gray-800">{{ subscriber.universidade }}</span>
            </div>
            <div class="w-full md:w-auto float-left md:mx-16">
                <i class="fas fa-book mr-2"></i> <!--https://fontawesome.com/icons/book?style=solid-->
                <span class="text-sm font-semibold text-gray-800">{{ subscriber.curso }}</span>
            </div>
            <form class="w-full md:w-auto float-right md:mx-4">
                {% csrf_token %}
                <button type="submit" formmethod="post" formaction="{{ current_page|addstr:'refuse-'|addstr:subscriber.pk|addstr:'/' }}" class="bg-red-700 hover:bg-red-500 text-white font-bold py-2 px-4 rounded-full ml-2 mt-4 md:mt-0">Recusar</button>
            </form>
            <form class="w-full md:w-auto float-right md:mx-4">
                {% csrf_token %}
                <button type="submit" formmethod="post" formaction="{{ current_page|addstr:'hire-'|addstr:subscriber.pk|addstr:'/' }}" class="bg-green-700 hover:bg-green-500 text-white font-bold py-2 px-4 rounded-full ml-2 mt-4 md:mt-0">Contratar</button>
            </form>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}