WebApp/urls.py
from django.urls import path, include
from .views import home, login_page, login_attempt, register_page, logout_page, profile_page


# urls de responsabilidade do app WebApp. app_name é uma referência
# para encontrar as urls mais facilmente.

app_name = 'webapp'
urlpatterns = [
    path('', home, name='home_page'),
    path('login/', login_page, name='login_page'),
    path('login/try/', login_attempt),
    path('logout/', logout_page, name='logout_page'),
    path('register/', register_page, name='register_page'),
    path('student/', include('EstudanteProfile.urls', namespace='estudante')),
    path('business/', include('EmpresaProfile.urls', namespace='empresa')),
    path('<username>/', profile_page, name='profile_page'),
]

freelance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('WebApp.urls', namespace='webapp'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WebApp/models.py
from django.db import models

# Create your models here.

WebApp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, reverse, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, Http404, HttpResponseRedirect


# Create your views here.
def home(request):
    """
    Renderiza o html da mainpage caso o usuário não esteja logado. Do contrário o envia para a página devida
    :param request:
    :return: renderização do html
    """

    if hasattr(request.user, 'empresaprofile'):
        return HttpResponseRedirect(reverse('webapp:empresa:home_page'))
    elif hasattr(request.user, 'estudanteprofile'):
        return HttpResponseRedirect(reverse('webapp:estudante:home_page'))
    return render(request, 'pages/home.html')


def register_page(request):
    """
    rendereiza o a tela de escolher o tipo de cadastro
    :param request:
    :return:
    """

    return render(request, 'pages/newaccount.html', {'url_empresa': reverse('webapp:empresa:register_page'),
                                               'url_estudante': reverse('webapp:estudante:register_page')})


def login_page(request):
    """
    Renderiza a página de login
    :param request:
    :return:
    """
    return render(request, 'pages/login.html')


def login_attempt(request):
    """
    Loga um usuário
    :param request:
    :return:
    """
    if request.method != 'POST':
        raise Http404("Page not found")
    username = request.POST.get('username')
    password = request.POST.get('password')

    if username[0] is not '@':
        username = '@' + username

    user = authenticate(username=username, password=password)

    if user is None:
        return render(request, 'pages/login.html', {'wrong_credentials': True})

    login(request, user)
    return HttpResponseRedirect(reverse('webapp:home_page'))


@login_required
def logout_page(request):
    """
    Desloga um usuário
    :param request:
    :return:
    """
    logout(request)
    return HttpResponseRedirect(reverse('webapp:home_page'))


def profile_page(request, username):
    """
    Mostra os dados de um usuário
    :param request:
    :param username: usuario em questão
    :return:
    """
    user = get_object_or_404(User, username=username)
    extends = ''
    if request.user.is_anonymous:
        extends = 'webapp-navbar.html'
    else:
        if hasattr(request.user, 'estudanteprofile'):
            extends = 'student-navbar.html'
        elif hasattr(request.user, 'empresaprofile'):
            extends = 'business-navbar.html'

    return render(request, 'pages/webapp-profile_page.html', {'user': user,
                                                              'extends': extends})

WebApp/templates/pages/home.html
{% extends "webapp-navbar.html" %}
{% load staticfiles %}
{% block content %}
    <div class="flex flex-col lg:flex-row justify-around lg:h-screen bg-login">
        <div class="m-5 lg:w-1/5 lg:my-auto flex flex-col justify-center text-center text-purple-900 bg-white p-12 xl:p-16 rounded-full border-8 border-purple-900">
            <i class="fas fa-tv fa-9x"></i>
            <div class="flex flex-col">
                <h2 class="font-semibold text-xl my-4">Tudo digital!</h2>
                <span class="text-justify">
                    Com tudo digital, tudo fica fácil!<br>
                    Aproveite uma plataforma amigável e eficiente para encontrar colaboradores ou propostas de emprego!
                </span>
            </div>
        </div>
        <div class="m-5 lg:w-1/5 lg:my-auto flex flex-col justify-center text-center text-white bg-purple-900 p-12 xl:p-16 rounded-full border-8 border-white">
            <i class="fas fa-map-marker-alt fa-9x"></i>
            <div class="flex flex-col">
                <h2 class="font-semibold text-white text-xl my-4">Pertinho de você!</h2>
                <span class="text-justify">
                    Aqui você encontra os melhores projetos e colaboradores, com as condições ideais para você. <br>E o melhor de tudo: <span class="font-semibold">Pertinho da sua casa!</span>
                </span>
            </div>
        </div>
        <div class="m-5 lg:w-1/5 lg:my-auto flex flex-col justify-center text-center text-purple-900 bg-white p-12 xl:p-16 rounded-full border-8 border-purple-900">
            <i class="fas fa-search fa-9x"></i>
            <div class="flex flex-col">
                <h2 class="font-semibold text-purple-900 text-xl my-4">Facilidade de encontrar o que você procura!</h2>
                <span class="text-justify">
                    Após se cadastrar, basta divulgar ou buscar uma proposta e você rapidamente receberá uma resposta!
                </span>
            </div>
        </div>
        <div class="m-5 lg:w-1/5 lg:my-auto flex flex-col justify-center text-center text-white bg-purple-900 p-12 xl:p-16 rounded-full border-8 border-white">
                <i class="fas fa-chart-pie fa-9x"></i>
            <div class="flex flex-col">
                <h2 class="font-semibold text-white text-center text-xl my-4">Só benefícios!</h2>
                <span class="text-justify">
                    Com o freelance-project, você rapidamente verá seus lucros subindo!
                </span>
            </div>
        </div>
    </div>
</div>
{% endblock %}

WebApp/templates/pages/login.html
{% extends "webapp-navbar.html" %}
{% block content %}
<div class="flex flex-wrap font-sans md:h-screen w-full bg-login">
    <div class="flex flex-col justify-center md:w-1/2">
        <div class="mx-auto text-center w-full md:w-3/4 bg-white border-8 border-purple-900 rounded-full p-6 md:p-10 my-10">
            <h1 class="font-bold mb-4 text-2xl md:text-5xl ml-4 text-purple-900">Freelance-project</h1>
            <p class="text-justify text-sm md:text-base md:text-1xl md:ml-8">
                Encontre colaboradores ou propostas de emprego com uma facilidade impressionante!
                Basta se cadastrar e começar a usar!
            </p>
        </div>
    </div>
    <div class="flex flex-col justify-center w-full md:w-1/2 mb-24 md:my-0">
        <div class="flex flex-wrap justify-center">
            <form action="{% url 'webapp:login_page' %}try/" method="post" class="bg-white shadow-lg rounded px-2 md:px-8 py-8 md:py-16">
                {% csrf_token %}
                <div class="text-center">
                    <h2 class="text-xl md:text-2xl font-semibold text-gray-700 mb-2">Login</h2>
                    <hr class="hr-gray mb-4">
                </div>
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2 ml-2" for="email">Nome de usuário</label>
                    <input name="username" class="shadow appearance-none border rounded w-full py-2 px-5 text-gray-700" id="email" type="text" placeholder="Nome de usuário" required>
                </div>
                {% if not wrong_credentials %}
                <div class="mb-6">
                {% else %}
                <div>
                {% endif %}
                    <label class="block text-gray-700 text-sm font-bold mb-2 ml-2" for="password">Senha</label>
                    <input name="password" class="shadow appearance-none border rounded w-full py-2 px-5 text-gray-700" id="password" type="password" placeholder="Senha" required>
                </div>
                {% if wrong_credentials %}
                <div class="mb-6">
                    <span style="color: red">Usuário inexistente</span>
                </div>
                {% endif %}
                <div class="flex items-center justify-center mb-4">
                    <input type="submit" class="bg-purple-700 hover:bg-purple-900 text-white font-bold py-2 px-4 rounded-full mr-2" value="Entrar">
                    <a href="{% url 'webapp:register_page' %}" class="bg-purple-700 hover:bg-purple-900 text-white font-bold py-2 px-4 rounded-full ml-2">Cadastrar</a>
                </div>
                <p class="text-center text-gray-600 text-xs">&copy;2019 Grupo 24 SCC-504</p>
            </form>
        </div>
    </div>
</div>
{% endblock %}

WebApp/templates/pages/newaccount.html
{% extends "webapp-navbar.html" %}
{% block content %}
{% load staticfiles %}
<div class="flex flex-wrap font-sans lg:h-screen bg-login">
    <!--Estudante-->
    <div class="flex flex-wrap lg:w-1/2 mb-10 lg:mb-0">
        <div class="mx-auto my-auto w-10/12 lg:w-2/3">
            <div class="bg-white overflow-hidden rounded-lg shadow-md">
                <img alt="student-profile" class="block h-auto w-full" src="{% static 'assets/student-profile.jpg' %}">
                <div class="flex flex-col p-2 md:p-4 text-center">
                    <h2 class="text-2xl font-bold">Estudante</h2>
                    <p class="text-gray-700 text-sm">
                        Estou a procura de uma proposta!
                    </p>
                </div>
                <div class="flex items-center justify-center p-2 md:p-4">
                    <a href="{{ url_estudante }}" class=" btn bg-purple-700 hover:bg-purple-900 text-white font-bold py-2 px-5 md:py-3 md:px-8 rounded-full">Escolher</a>
                </div>
            </div>
        </div>
    </div>
    <!--Empresa-->
    <div class="flex flex-wrap lg:w-1/2 mb-10 lg:mb-0">
        <div class="mx-auto my-auto w-10/12 lg:w-2/3">
            <div class="bg-white overflow-hidden rounded-lg shadow-md">
                <img alt="company-profile" class="block h-auto w-full" src="{% static 'assets/company-profile.jpg' %}">
                <div class="flex flex-col p-2 md:p-4 text-center">
                    <h2 class="text-2xl font-bold">Empresa</h2>
                    <p class="text-gray-700 text-sm">
                        Quero divulgar minha proposta!
                    </p>
                </div>
                <div class="flex items-center justify-center p-2 md:p-4">
                    <a href="{{ url_empresa }}" class="btn bg-purple-700 hover:bg-purple-900 text-white font-bold py-2 px-5 md:py-3 md:px-8 rounded-full">Escolher</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

WebApp/templates/pages/webapp-profile_page.html
{% extends extends %}
{% block title %}
<title>{{ user.username }}</title>
{% endblock %}
{% block content %}
<div class="w-full flex flex-wrap justify-center">
    <header class="w-full h-32 md:h-48 header-student">
        <div class="w-1/2 md:w-1/3 flex justify-center">
            {% if user.estudanteprofile %}
            <img src="{{ user.estudanteprofile.profile_pic.url }}" alt="icone-usuario"
            class=" float-left rounded-full border-8 border-white w-32 h-32 md:w-48 md:h-48 mt-8 mb-8 mt-16 md:mt-24 shadow-md">
            {% else %}
            <img src="{{ user.empresaprofile.profile_pic.url }}" alt="icone-usuario"
            class=" float-left rounded-full border-8 border-white w-32 h-32 md:w-48 md:h-48 mt-8 mb-8 mt-16 md:mt-24 shadow-md">
            {% endif %}
        </div>
    </header>
    <div class="ml-auto md:ml-0 w-1/2 mt-2 flex flex-col">
        <span class="float-right font-semibold text-blue-600 text-xl md:text-3xl">{{ user.first_name }} {{ user.last_name }}</span>
        <span class="text-gray-700 text-lg font-semibold">({{ user }})</span>
    </div>
    <div class="w-5/6 md:w-2/3 mt-16 flex flex-col shadow-lg bg-white">
        <h2 class="text-2xl md:text-4xl font-semibold text-blue-600 text-center mb-8 pt-2">Perfil</h2>
        <div class="w-full flex justify-center mb-8">
            <div class="w-4/5 md:w-3/5 flex flex-col">
                {% if user.estudanteprofile %}
                <h3 class="text-xl md:text-2xl font-semibold text-blue-600 mb-2">Descrição</h3>
                <p class="text-gray-800 text-justify mb-4">
                    {% if user.estudanteprofile.descricao %}
                        {{ user.estudanteprofile.descricao }}
                    {% else %}
                        No description
                    {% endif %}
                </p>
                <h3 class="text-xl md:text-2xl font-semibold text-blue-600 mb-2">Informações acadêmicas</h3>
                <div class="flex flex-wrap">
                    <span class="text-gray-900 mr-2 font-semibold">Universidade:</span>
                    <span class="text-sm md:text-base text-gray-800">{{ user.estudanteprofile.universidade }}</span>
                </div>
                <div class="flex flex-wrap">
                    <span class="text-gray-900 mr-2 font-semibold">Curso:</span>
                    <span class="text-sm md:text-base text-gray-800">{{ user.estudanteprofile.curso }}</span>
                </div>
                <div class="flex flex-wrap">
                    <span class="text-gray-900 mr-2 font-semibold">Ano de formatura:</span>
                    <span class="text-sm md:text-base text-gray-800">{{ user.estudanteprofile.previsao_formatura }}</span>
                </div>
                {% else %}
                <h3 class="text-xl md:text-2xl font-semibold text-blue-600 mb-2">Descrição</h3>
                <p class="text-gray-800 text-justify mb-4">
                    {% if user.empresaprofile.description %}
                        {{ user.empresaprofile.description}}
                    {% else %}
                        No description
                    {% endif %}
                </p>
                <h3 class="text-xl md:text-2xl font-semibold text-blue-600 mb-2">Informações adicionais</h3>
                <div class="flex flex-wrap">
                    <span class="text-gray-900 mr-2 font-semibold">Cidade:</span>
                    <span class="text-sm md:text-base text-gray-800">{{ user.empresaprofile.cidade }}</span>
                </div>
                <div class="flex flex-wrap">
                    <span class="text-gray-900 mr-2 font-semibold">Área de atuação:</span>
                    <span class="text-sm md:text-base text-gray-800">{{ user.empresaprofile.area }}</span>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}